### ISSUE TITLE
Can Pokemon Gaia Be Randomized?

### ISSUE THREAD

**Issue by NeptuneAirslash** [Dabomstew/universal-pokemon-randomizer#143]
I'm really wanting to do an LP of Pokemon Gaia. However, after I tried to randomize the game (via Universal Pokemon Randomizer) I got an error saying the following.

Randomizer Version: 1720

ROM: Fire Red (U) 1.0 (ROM Hack)

Code: BPRE

Reported Support Level: No Static Pokemon

java.lang.ArrayIndexOutOfBoundsException: -126287869

at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.readWildArea(Gen3RomHandler.java:1286)

at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.getEncounters(Gen3RomHandler.java:1232)

at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomEncounters(AbstractRomHandler.java:553)

at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:368)

at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

**Comment by CharmyBee99** [comment]
Rom hack support isn't actually planned (at least according to the FAQs), so I'm sorry to say but no, it's not gonna work for now as there's no official support for Rom hacks.
