### ISSUE TITLE
Problem with Gen 4 NTEVO Roms

### ISSUE THREAD

**Issue by PK-Tanooki** [Dabomstew/universal-pokemon-randomizer#28]
There are a series of roms for the DS Pokemon games that remove trade evolutions (Located here: http://pokemonntevoroms.blogspot.com/). The files for Pokemon Black/White and Black/White 2 work fine with the randomizer, but the Pokemon Heart Gold/Soul Silver and Diamond/Pearl/Platinum files don't. I'm wondering why that is.

**Comment by PK-Tanooki** [comment]
I get this error whenever I try to load Soul Silver:

Randomizer Version: 1720
ROM: Pokemon SoulSilver (U)
Code: IPGE
Reported Support Level: Complete

java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.dabomstew.pkrandom.newnds.NARCArchive.readNitroFrames(NARCArchive.java:170)
	at com.dabomstew.pkrandom.newnds.NARCArchive.<init>(NARCArchive.java:21)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.readNARC(AbstractDSRomHandler.java:110)
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.loadedROM(Gen4RomHandler.java:294)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.loadRom(AbstractDSRomHandler.java:61)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$2.run(RandomizerGUI.java:1003)
