### ISSUE TITLE
Cant make a randomizer for blaze black 2

### ISSUE THREAD

**Issue by co0kieco0kie** [Dabomstew/universal-pokemon-randomizer#29]
Im not sure if it is a hack but getting this error msg. (Btw using macbook air)
Randomizer Version: 1720
ROM: Pokemon Black 2 (U)
Code: IREO
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeStaticPokemon(AbstractRomHandler.java:1930)
	at com.dabomstew.pkrandom.Randomizer.maybeChangeAndLogStaticPokemon(Randomizer.java:748)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:339)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

If you can do something thx! Really wanna play randomizer nuzlocke!

**Comment by co0kieco0kie** [comment]
Never mind saw the problem in some other persons issue
