### ISSUE TITLE
odd error coming up

### ISSUE THREAD

**Issue by Emilinrose** [Dabomstew/universal-pokemon-randomizer#3]
I keep getting an error message that is confusing me.
java.lang.ArrayIndexOutOfBoundsException: 46070
	at com.dabomstew.pkrandom.constants.Gen3Constants.poke3GIndexToNum(Gen3Constants.java:340)
	at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.getIngameTrades(Gen3RomHandler.java:2571)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:431)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1528)

this occurs even when i'm not changing the in game trades. In fact it does it when i don't touch anything to test it.

i also get this error on occasion, this one is irritating as heck.

java.lang.NullPointerException
	at com.dabomstew.pkrandom.Randomizer.maybeLogBaseStatAndTypeChanges(Randomizer.java:528)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:188)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1528)

**Comment by Dabomstew** [comment]
Possibly related to attempting to randomize a ROM hack or otherwise unclean file. Don't really have enough information to investigate for the time being.
