### ISSUE TITLE
Blaze Black 2 Randomizer not Working?

### ISSUE THREAD

**Issue by BrandonTheBeast** [Dabomstew/universal-pokemon-randomizer#37]
Everytime I try to randomize my Blaze Black 2 rom I get this message: 
![image](https://cloud.githubusercontent.com/assets/25195687/22056601/d84afc96-dd2e-11e6-9c77-1b44ca7be862.png)

Randomizer Version: 1720
ROM: Pokemon Black 2 (U)
Code: IREO
Reported Support Level: Complete

java.lang.NullPointerException
	at com.dabomstew.pkrandom.Randomizer.maybeChangeAndLogStaticPokemon(Randomizer.java:762)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:339)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

I don't know what the problem is, maybe my rom isn't clean but there aren't any other decently available roms out there, so someone help please!

**Comment by Dabomstew** [comment]
Gen4+ hacks aren't supported.
