### ISSUE TITLE
Randomizing Pokemon Black/White won't work

### ISSUE THREAD

**Issue by JohnnyTrex** [Dabomstew/universal-pokemon-randomizer#42]
Whenever I attempt to randomize Pokemon Black or White (unknown for other nds games) it gives this error code...

Randomizer Version: 1720
ROM: Pokemon White (U)
Code: IRAO
Reported Support Level: Complete

com.dabomstew.pkrandom.exceptions.RandomizerIOException: java.io.FileNotFoundException: C:\Users\Johnathan\Downloads\Johanthan's\UPRandomizer-2-win\Pokemon White 02\18\17.nds (The system cannot find the path specified)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.saveRom(AbstractDSRomHandler.java:88)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:522)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)
Caused by: java.io.FileNotFoundException: C:\Users\Johnathan\Downloads\Johanthan's\UPRandomizer-2-win\Pokemon White 02\18\17.nds (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at java.io.RandomAccessFile.<init>(Unknown Source)
	at com.dabomstew.pkrandom.newnds.NDSRom.saveTo(NDSRom.java:227)
	at com.dabomstew.pkrandom.romhandlers.AbstractDSRomHandler.saveRom(AbstractDSRomHandler.java:86)
	... 2 more

Can you please tell me how to resolve this issue.

Thank you

**Comment by Dabomstew** [comment]
It seems like the ROM filename you specified to save to is weird in this case, you should try using a filename without special characters.
