### ISSUE TITLE
Help Couldnt randomize bloody platin

### ISSUE THREAD

**Issue by galotta** [Dabomstew/universal-pokemon-randomizer#53]
I got This error mesage
Randomizer Version: 1720
ROM: Pokemon Platinum (G)
Code: CPUD
Reported Support Level: No Static Pokemon

java.lang.NullPointerException
	at com.dabomstew.pkrandom.romhandlers.Gen4RomHandler.setTrainers(Gen4RomHandler.java:1377)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.rivalCarriesStarter(AbstractRomHandler.java:1069)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:304)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

**Comment by Dabomstew** [comment]
Gen4+ hacks aren't supported.
