### ISSUE TITLE
Moemon Fire Read ROM - Can't Randomize

### ISSUE THREAD

**Issue by ThisNekoGuy** [Dabomstew/universal-pokemon-randomizer#54]
Hey, I'm new to GitHub (I've only now joined for this reason) and I've encountered an issue with randomizing the game. Can someone help me to resolve the issue?

The error log says:

Randomizer Version: 1720
ROM: Fire Red (U) 1.0 (ROM Hack)
Code: BPRE
Reported Support Level: No Static Pokemon

java.lang.ArrayIndexOutOfBoundsException: 2058
	at com.dabomstew.pkrandom.romhandlers.Gen3RomHandler.getTrainers(Gen3RomHandler.java:1378)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.randomizeTrainerPokes(AbstractRomHandler.java:915)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:292)
	at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

------------------------------------------------------------------------------------

The only thing I can do here is guess that it had some kind of problem with randomizing the trainers' Pokémon.

**Comment by CharmyBee99** [comment]
I bet that it's your ROM, as the randomizer has full support for Fire Red, did you use a pre-patched ROM you found on the internets?
For randomizing ROM hacks, I always recommend downloading the original patch then applying it on a clean ROM and not using and sketchy pre-patched ROMs.
To my knowledge, ROM hacks which modify only stuff like graphics,  sound, text or even actual small romhacks should work. (Because I have randomized text hacks (poorly translated versions of the originals)) Even ones like Vietnamese Crystal have a special header in the randomizer.

**Comment by ThisNekoGuy** [comment]
I used the "Squirrel's" version of the Fire Red ROM and patched it with the IPS and it randomizes fine just like that.
But when I touch the ROM directly (like fixing the positioning of the sprites in battle because they're not lining up with the menu), the randomizer gets an error.
Which, I wouldn't understand why that would be if I all I did was alter the y-axis values the sprites show up on in battle.

The only way I found to avoid this was to randomize it first and then fix all the little stuff but that gets really tedious.
