### ISSUE TITLE
Impossible Evos aren't working

### ISSUE THREAD

**Issue by GamecubeGuy** [Dabomstew/universal-pokemon-randomizer#78]
Hey, I was playing Pokemon Emerald, and I just wanted to turn on impossible Evos. However, when doing so, I get an error: 
java.lang.NullPointerException
at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:394)at com.dabomstew.pkrandom.gui.RandomizerGUI$3.run(RandomizerGUI.java:1957)

I did edit certain areas using AdvancedMap and changed dialogue using AdvancedText, so that may have something to do with it. If you could help me figure out what I should do to fix this, I would greatly appreciate it. Thank you for your time.

**Comment by RCTMASTA** [comment]
Remove impossible evos using the tool and THEN make your changes...?

**Comment by GamecubeGuy** [comment]
I want to make impossible work, is there any way I can do that?

**Comment by RCTMASTA** [comment]
Sorry, I worded that poorly. What i meant to say was:
Do the impossible evos change using the tool, and then modify the ROM with your changes using AdvanceMap and Advanced Text.

**Comment by GamecubeGuy** [comment]
That's the problem, when I try to save it, it gives me that error, so I can't modify the rom after I change it because it won't allow me to change it to begin with.
